################################
# REST - example configuration #
################################

# These are example definition of REST component.
# In order to use the component, you first must call Rest::setConfig($pathToYourConfig).
Rest:
    ExampleApi:
        CompilePath: /var/tmp
        Router:
            Class: \Webiny\Component\Rest\{test}\{mock}\{class}
            Path: /services/{test}/{mock}/{class}
            Normalize: true
    SomeOtherApi:
        Cache: someCacheService
        Security:
            Role: ROLE_SECRET
            Firewall: Admin
        RateControl:
            Limit: 60
            Interval: 1 # in minutes
            Penalty: 10 # in minutes
        Environment: production